# --- !Ups
CREATE TABLE Accounts (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(200) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Bookmarks (
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  url VARCHAR(250) NOT NULL,
  tags VARCHAR(250),
  acc_id INT NOT NULL,
  FOREIGN KEY (acc_id) REFERENCES Accounts(id),
  PRIMARY KEY (id)
);

# --- !Downs
DROP TABLE Bookmarks;
DROP TABLE Accounts;